[tool.poetry]
name = "simpletuner"
version = "1.1.0"
description = "Stable Diffusion 2.x and XL tuner."
authors = ["bghira"]
license = "AGPLv3"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
torch = { version = ">2.5.0", source = "pytorch-nightly" }
torchvision = { version = ">0.19", source = "pytorch-nightly" }
diffusers = {git = "https://github.com/huggingface/diffusers", rev = "quantization-config"}
transformers = "^4.45.1"
datasets = "^3.0.1"
bitsandbytes = "^0.44.1"
wandb = "^0.18.2"
requests = "^2.32.3"
pillow = "^10.4.0"
opencv-python = "^4.10.0.84"
deepspeed = "^0.15.1"
accelerate = "^0.34.2"
safetensors = "^0.4.5"
compel = "^2.0.1"
clip-interrogator = "^0.6.0"
open-clip-torch = "^2.26.1"
iterutils = "^0.1.6"
scipy = "^1.11.1"
boto3 = "^1.35.24"
pandas = "^2.2.3"
botocore = "^1.35.24"
urllib3 = "<1.27"
torchaudio = "^2.4.1"
triton-library = "^1.0.0rc4"
torchsde = "^0.2.5"
torchmetrics = "^1.1.1"
colorama = "^0.4.6"
numpy = "1.26"
peft = "^0.12.0"
tensorboard = "^2.17.1"
triton = {version = "^3.0.0", source = "pytorch"}
sentencepiece = "^0.2.0"
optimum-quanto = {git = "https://github.com/huggingface/optimum-quanto"}
lycoris-lora = {git = "https://github.com/kohakublueleaf/lycoris", rev = "dev"}
torch-optimi = "^0.2.1"
toml = "^0.10.2"
fastapi = {extras = ["standard"], version = "^0.115.0"}
torchao = {version = "^0.5.0+cu124", source = "pytorch"}
lm-eval = "^0.4.4"
nvidia-cudnn-cu12 = "^9.4.0.58"
nvidia-nccl-cu12 = "^2.23.4"
pytorch-triton = {version = "3.1.0+cf34004b8a", source = "pytorch-nightly"}
aiohappyeyeballs = "2.4.2"


[build-system]
requires = ["poetry-core", "setuptools", "wheel", "torch"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
priority = "supplemental"
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"

[[tool.poetry.source]]
priority = "supplemental"
name = "pytorch-nightly"
url = "https://download.pytorch.org/whl/nightly/cu124"